In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import statsmodels.formula.api as smf
import json

In [3]:
con = pd.read_csv(r"C:\Users\thegr\Downloads\video-game-sales.csv")
con.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [4]:
game = pd.read_csv(r"C:\Users\thegr\Downloads\Extracted_video_games_data.csv")
game.head()

,Pos,Game,Game.1,Console,Publisher,Developer,VGChartz Score,Critic Score,User Score,Total Shipped,Total Sales,NA Sales,PAL Sales,Japan Sales,Other Sales,Release Date,Last Update,Genre
0,1,NaN,God of War,Series,Sony Computer Entertainment,SIE Santa Monica Studio,NaN,NaN,NaN,51.00m,NaN,NaN,NaN,NaN,NaN,22nd Mar 05,04th Mar 20,Action
1,2,NaN,Warriors,Series,KOEI,Omega Force,NaN,NaN,NaN,45.26m,NaN,NaN,NaN,NaN,NaN,30th Jun 97,24th Mar 20,Action
2,3,NaN,Devil May Cry,Series,Capcom,Capcom,NaN,NaN,NaN,22.00m,NaN,NaN,NaN,NaN,NaN,16th Oct 01,03rd Feb 20,Action
3,4,NaN,Dynasty Warriors,Series,Unknown,Omega Force,NaN,NaN,NaN,21.00m,NaN,NaN,NaN,NaN,NaN,NaN,24th Mar 20,Action
4,5,NaN,Grand Theft Auto V,PS3,Rockstar Games,Rockstar North,NaN,9.4,NaN,NaN,20.32m,6.37m,9.85m,0.99m,3.12m,17th Sep 13,NaN,Action

Going through the data that I found online, only two of them held something of value to me, and what I want to play around with. However, I noticed how large the data is in both, even if one focuses on the games, and the other focuses more on the consoles. So, I think I want to try and focus on a certain few consoles and break down the data and compare my findings to see which was the most profitable. I personally believe that it would be the Wii, as it was pretty revalutionary at the time with it's motion controls, and seeing how well the games sold that nintendo made will help prove that. Others I will look it that released at that time would be PS2, PS3, Xbox 360, etc. That way, I limit myself to a certain few and don't try and spend days on end going through data.

In [5]:
con.keys()

Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')